drop table if exists bookmarks;


create table bookmarks (
  id INTEGER primary key generated by default as identity,
  mark VARCHAR(30)
);

insert into bookmarks (mark)
values 
     ('Chapter One'),
     ('Chapter Two'),
     ('Chapter Three'),
     ('Chapter Four'),
     ('Chapter Five'),
     ('Chapter Six'),
     ('Chapter Seven'),
     ('Chapter Eight'),
     ('Chapter Nine'),
     ('Chapter Ten');
    
  
  